all: true
dir: './'
filename: mocks_test.go
force-file-write: true
formatter: goimports
log-level: info
structname: '{{.Mock}}{{.InterfaceName}}'
pkgname: '{{.SrcPackageName}}'
recursive: false
require-template-schema-exists: true
template: testify
template-schema: '{{.Template}}.schema.json'
packages:
  psmarcin.github.com/open-ynab-sync:
    config:
      filename: mock_test.go
      pkgname: 'main'
    interfaces:
      goCardlesser:
      ynaber:

  psmarcin.github.com/open-ynab-sync/cmd/link/api:
    config:
      filename: gocardless.go
      dir: 'cmd/link/api/apimock'